### PR TITLE
theme final

### PR DESCRIPTION
**Pull request by emocentmagar**

### CODE REVIEW

**Comment by lambu** [comment]
merged!

On 13 January 2015 at 14:33, Lalit Thapa <notifications@github.com> wrote:

> Merged #78 <https://github.com/emocentmagar/futsalnepal/pull/78>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emocentmagar/futsalnepal/pull/78#event-217930652>.
>



-- 
<h1>SUbash</h1> <h2>subash</h2>

**Comment by lambu** [comment]
Hi emocentmagar/futsaln,

I'd like to add you to my professional network on LinkedIn.

- Subash

Confirm that you know Subash: https://www.linkedin.com/e/v2?e=0-imdnfzft-40&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=B0kyNN6H&invitationId=6120608619135324161








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-imdnfzft-40&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHEZYlrL7lJcwAAAVPDPxSt0wTaas7sIw_VCirpb0LmdZR3Epj_dwSWxbDyfF6ozqZazCBqmGMYiXBy4n-qIeAnwShDCyhm3xeXraEEHZn_oiv__jChDVL_DskZXUl6Mn8-6r9XjeyQ6AM86tHKH5BSjKxJMQnwc3sJljjT3Y4qsr8UyQ2aUd_kj_MKQPI7RtBZ&eid=0-imdnfzft-40


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-imdnfzft-40&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Pracanda** [comment]
Kta ho.. Futsal ko mbl version ko theme ho?

**Comment by lambu** [comment]
Subash Lamsal would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-2hsm65-immx2q5v-se&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=B0kyNN6H&invitationID=6120608619135324161

View Subash Lamsal&#39;s profile: https://www.linkedin.com/e/v2?e=-2hsm65-immx2q5v-se&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=B0kyNN6H&invitationID=6120608619135324161





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-2hsm65-immx2q5v-se&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-2hsm65-immx2q5v-se&loid=AQFn4wXd2O8hBQAAAVPlqFy1ro-BNfieqTzRFttLCzoiY-f72YX6_MxXejQ4gjNFrXMwIvHwZr3Q2SmfdZqaEyquFiYyWtozFBoXxRtH0FSDsquRXldLVttQoxOFy-2-npChifnmcQRCyYWlJzA6iKNMyaOFnvcgjrwQwE1_VcWx4NBJy9uvSKYAJuUQHKYpmivC

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-2hsm65-immx2q5v-se&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
